[package]
name = "websessn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonwebtoken = "8.2.0"
lazy_static = "1.4.0"
serde = { version = "1.0.150", features = ["derive"] }
webauthn-rs = "0.4.8"
